# Generated by Django 4.2.4 on 2023-08-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes_problemas/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Open311ReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin título', max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(default='Otra', max_length=100, verbose_name='Categoría')),
                ('estatus', models.CharField(default='Pendiente', max_length=50, verbose_name='Estado')),
                ('direccion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id_ciudadano', models.CharField(max_length=20, verbose_name='id Ciudadano')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes_problemas/', verbose_name='Imagen')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos_reportes/', verbose_name='Archivo Adjunto')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin título', max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estatus', models.CharField(default='Pendiente', max_length=50, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id_ciudadano', models.CharField(max_length=20, unique=True, verbose_name='id Ciudadano')),
                ('id_funcionario', models.CharField(max_length=20, unique=True, verbose_name='id funcionario')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos_solicitudes/', verbose_name='Archivo Adjunto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo o Puesto')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento o Área')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('horario_trabajo', models.CharField(max_length=100, verbose_name='Horario de Trabajo')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad o Experiencia')),
                ('foto_perfil', models.ImageField(blank=True, upload_to='funcionarios/', verbose_name='Foto de Perfil')),
                ('id_funcionario', models.CharField(max_length=20, unique=True, verbose_name='id funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='AvanceReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avance', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Avance')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('funcionario', models.CharField(max_length=20, unique=True, verbose_name='id Funcionario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportessolicitudes.open311reporteproblema')),
            ],
        ),
    ]
