# Generated by Django 4.2.4 on 2023-08-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportessolicitudes', '0003_usuariofuncionario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinformacion',
            name='comentario',
            field=models.TextField(default='sin responder aún', verbose_name='Comentario'),
            preserve_default=False,
        ),
    ]
