# Generated by Django 4.2.4 on 2023-08-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportessolicitudes', '0004_solicitudinformacion_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofuncionario',
            name='comentario',
        ),
    ]
