# Generated by Django 4.2.4 on 2023-08-29 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportessolicitudes', '0005_remove_usuariofuncionario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofuncionario',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
