# Generated by Django 4.2.4 on 2023-08-29 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportessolicitudes', '0006_usuariofuncionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofuncionario',
            name='user',
        ),
        migrations.AlterField(
            model_name='usuariofuncionario',
            name='id_funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
